### ISSUE TITLE
After doing all instructions, it doesn't show server/chats/:id

### ISSUE THREAD

**Issue by AnerGcorp** [Urigo/WhatsApp-Clone-Server#1242]
I am new to` react` and `graphql`, I don't know where  I made mistake, I tried full version, I just cloned the repository and did what is in instructions, but after doing them all there is an issue in my cloned project after signing in I can't see `localhost:3000/chats/:id `, it doesn't show anything. when I open the console on browser I see this message:
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AnimatedSwitch, TransitionMotion. Also there has `Error` but it doesn't show any anything[ bundle.esm.js:76].  
 Can anybody help me

**Comment by Urigo** [comment]
Just pushed a new update that should fix you issue (but not the warnings)

Please let me know if the app doesn't run for you

Thank you for reporting
