### ISSUE TITLE
yarn codegen fails

### ISSUE THREAD

**Issue by hugo4711** [Urigo/WhatsApp-Clone-Server#1295]
➜ yarn codegen
yarn run v1.22.0
$ graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./types/graphql.d.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ✔ Generate ./types/unsplash.d.ts

 Found 1 error

  ✖ ./types/graphql.d.ts
    Failed to load schema from ./modules/*/index.ts:

        Unable to find any GraphQL type defintions for the following pointers: ./modules/*/index.ts
        Error: Unable to find any GraphQL type defintions for the following pointers: ./modules/*/index.ts
    at Object.loadTypedefs (/Users/nolte/Documents/velian/rnd/react-whatsapp/WhatsApp-Clone-Server/node_modules/graphql-toolkit/dist/commonjs/loaders/load-typedefs.js:78:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.

Something went wrong
error Command failed with exit code 1.

**Comment by Urigo** [comment]
@hugo4711 just pushed a new version, could you try it again?

**Comment by hugo4711** [comment]
Seems to work! Thank you
