### ISSUE TITLE
Issue with command setting up apollo

### ISSUE THREAD

**Issue by dannyp32** [Urigo/WhatsApp-Clone-Server#134]
Hi I'm trying to run the following command and I get this error. Should the command say 0.4.0?

yarn add apollo-cache-inmemory@1.4.3 apollo-client@2.4.13 apollo-link@1.2.8 apollo-link-http@1.5.11 apollo-link-ws@1.0.14 apollo-utilities@1.1.3 graphql@14.1.1 react-apollo-hooks@4.0.0 subscriptions-transport-ws@0.9.15
yarn add v1.15.2
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "react-apollo-hooks" that matches "4.0.0"
? Please choose a version of "react-apollo-hooks" from this list: (Use arrow keys)
❯ 0.5.0-alpha.0 
  0.4.5 
  0.4.4 
  0.4.3 
  0.4.2 
  0.4.1 
  0.4.0 
  0.3.1 
  0.3.0 
  0.2.1 
  0.2.0 
  0.1.8 
  0.1.7 
  0.1.6 
  0.1.5 
  0.1.3 
  0.1.2 
  0.1.1 
  0.1.0 
  0.0.2 
  0.0.1

**Comment by Urigo** [comment]
@dannyp32 We've updated the tutorial and the repository to work with the latest versions.

Can you please try again using all the latest version and see if this is still a problem?

Thank you
Closing but please reopen if you get any issue or question!
