### ISSUE TITLE
Broken markdown link

### ISSUE THREAD

**Issue by kefimochi** [Urigo/WhatsApp-Clone-Server#1424]
![image](https://user-images.githubusercontent.com/47342588/83161186-f43aa000-a0bc-11ea-83cc-515581118100.png)
Was checking out the WhatsApp tutorial and noticed a broken markdown link [here](https://www.tortilla.academy/Urigo/WhatsApp-Clone-Tutorial/master/next/step/14), I believe the only difference is square brackets and link's name should be prior to the web address.

**Comment by Urigo** [comment]
ohh good one.  Thank you!
Such brain fart...
Fixed and will push a new version.

By the way, we've just added the ability to PR the whole tutorial and get actual recognition (even with the way [Tortilla](http://github.com/urigo/tortilla) manipulates the git history), so next time you could even submit a simple change and become one of the authors automatically!

We love help so if you or anyone who comes here get confused by who to contribute, feel free to ping us!
