### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by enriquemorenotent** [Urigo/WhatsApp-Clone-server#27]
The README is not offering much information about how to set up the system. All it offers is a broken link (https://github.com/Urigo/tortilla) showing me a 404 error.

Following the buttons also does not help much, since I land on a barely empty page.

(Also first issue! Yay! Great work, by the way :+1: )

**Comment by DAB0mB** [comment]
Your'e right, this was originally built as a step-by-step tutorial but then we decided to delay it for later. I will update the README file and make it more informative

**Comment by DAB0mB** [comment]
Just added README.md instructions
