### ISSUE TITLE
[Question] GraphQL and N+1 problem

### ISSUE THREAD

**Issue by CTOJoe** [Urigo/WhatsApp-Clone-Server#32]
Does this project touch on the N+1 problem with GrapqhQL by using dataloader or any other query batching? Looking through the source I do not see anything that takes this issue into consideration.

**Comment by darkbasic** [comment]
You are correct: tackling the N+1 problem is planned for a later chapter of the tutorial where we will cover performance optimizations.
Many more features like pagination are also planned.

**Comment by Urigo** [comment]
We would love to start collaborating on this already.

First we need to come up with the relevant use case here, where do you see Dataloader or a similar feature fit?
Then, we would want to measure performance before and after.  We would love help with creating a PR with a tool that measure and demonstrate the benefits.
Then, we would love a PR for master with the full solution.

After that we can take it and create a chapter out of it all.

Would love any help possible including comments on this issue

**Comment by CTOJoe** [comment]
I see Dataloader being used in providers. It would be a clear and concise example of why using providers is preferred over just using an entity in a resolver. Additionally it is a good example of how when we optimize a provider in one place, it is optimized everywhere it is injected.

Performance should be measured on how many queries hit the database more so than response time of each query. 

A simple example would be to select the same thing twice using an alias. Before Dataloader this should run two separate queries. This would also open up the ability in the future to talk about malicious queries and methods to mitigate them.

```graphql
query { 
  chat(chatId: "1") {
    name
  }
  sameChat: chat(chatId: "1") {
    name
  }
}
```

In the provider,  a new Dataloader can be initialized in the constructor so that cached entities can be destroyed when the provider with the provider (session scoped). Additionally the Dataloader can be primed on list loads asynchronously.

**Comment by Urigo** [comment]
We've just added the code that demonstrates the usage of `dataloader` as part of a performance chapter: https://www.tortilla.academy/Urigo/WhatsApp-Clone-Tutorial/master/next/step/17

Check this out and let us know how we can improve the chapter and the code!
