### ISSUE TITLE
Missing server/env.ts changes on tortilla

### ISSUE THREAD

**Issue by MStokluska** [Urigo/WhatsApp-Clone-Server#777]
Hi,

I might be missing something but server file env.ts is first introduced in step 13 on tortilla ( Server step 10.1 ) with just 2 lines.
```
export const origin = process.env.ORIGIN || 'http://localhost:3000';
export const port = process.env.PORT || 4000;
```
In server step 10.2 we are importing the following
```
import { secret, expiration } from '../env';
```
However both secret and expiration where not added to env file following tutorial on tortilla.
Same happens in step 14 on tortilla, server step 11.5:
```
import { resetDb as envResetDb } from '.env'
```
We are missing resetDb in env file on tortilla.

This is only a minor issue with tortilla rather than code as env file on git is correct and can be looked at in the repo however, as I am following this tutorial step by step it would be great if env file could be updated on tortilla too.

**Comment by Urigo** [comment]
true!

I've fixed it and will keep it open until I'll release a new version

Thank you!

**Comment by MStokluska** [comment]
Hi @Urigo 

Thank you, also, during step 14 - Migrating to PostgreSQL there's an issue with testing part. 
What happens is I'm keep getting this message : 
```
Jest did not exit one second after the test run has completed
```
As I understand it Jest need to be forced to exit when using async await with more than one await, I might be wrong on that, however, I eventually found a solution and then realized that your package.json
has it implemented
```
"test": "jest --runInBand --forceExit"
```
It would be great if that package.json update could be shown on tortilla as well.
Not sure if you would like me to create another issue or just keep tortilla issues in this issue?

Thank you

**Comment by Urigo** [comment]
right again, I've added and will release soon.

Thank you!

**Comment by Urigo** [comment]
released and deployed
