### ISSUE TITLE
Ident authentication failed - PostgreSQL 

### ISSUE THREAD

**Issue by MStokluska** [Urigo/WhatsApp-Clone-Server#803]
Hi there,

Not sure if this issue was only on my side, as I'm pretty new to postgresql, but when completing step 14 I had problems with connecting to my database with following error:
```
Ident authentication failed for user
```
Apparently reason for this is that client login uses ident based authentication method instead of password authentication mode.
All it takes to fix it is to edit pg_hba.conf file of postgresql and set  authorization method to "trust" and restart postgres.

I know your tutorial isn't about postgresql but I think it would be handy to mention about it, unless I did something wrong while installing my postgres.

Let me know what you think please,
Thank you

**Comment by Urigo** [comment]
thank you for that!
Can you maybe create a PR for the [text](https://github.com/Urigo/WhatsApp-Clone-Tutorial/blob/master/.tortilla/manuals/templates/step14.tmpl) and maybe also for the [code](https://github.com/Urigo/WhatsApp-Clone-Server) with your idea of how we should explain that?

**Comment by Urigo** [comment]
also the tutorial is also about Postgres, the more information you can add on Postgres the better

**Comment by MStokluska** [comment]
closing the issue as it was fixed through pr.
thanks Urigo.

**Comment by Urigo** [comment]
Thank you @MStokluska !
