### ISSUE TITLE
Whatsapp Clone, using Ionic, Stencil and Web Components

### ISSUE THREAD

**Issue by peterennis** [Urigo/WhatsApp-Clone-Server#849]
From here: https://medium.com/the-guild/fully-functional-whatsapp-clone-using-angular-graphql-apollo-typescript-and-postgresql-5479d83baaa4

**"Soon we will also release yet another version of the Whatsapp Clone, using Ionic, Stencil and Web Components."**

Where do I get more information on this project?

**Comment by Urigo** [comment]
Sounds like a duplicate of this: https://github.com/Urigo/WhatsApp-Clone-Client-React/issues/158

Are you willing to help us create it?

**Comment by peterennis** [comment]
@Urigo 

PR Here: https://github.com/ardatan/WhatsApp-Clone-client-Stencil/pull/28

1. Still some dev security issues e.g. lodash
2. Create account does nothing
3. Dark text for dark background is not good for data entry
4. Tests do not pass but the app builds and runs

What is the path forward to get a working test system?

**Comment by Urigo** [comment]
@peterennis nice!  that is a very good first step, thank you so much for that!

The first question is - do you want to create a full tutorial or just the end result?
If full tutorial, let's start by having a chat on how we can help and support you on that, I'm available to help for anyone who wants to contribute.

How about starting with a short video chat? my email is public on my Github profile

**Comment by peterennis** [comment]
What app/link do you use for video chat?

**Comment by Urigo** [comment]
Slack/Google Hangouts/anything else you wish for

**Comment by peterennis** [comment]
@Urigo 
Send me a slack link and we can try to connect.

**Comment by Urigo** [comment]
@peterennis just reach out through Hangouts or email: uri.goldshtein at gmail
